### ISSUE TITLE
Plugin internal instances stored in the host IMemoryCache appear to not be castable.

### ISSUE THREAD

**Issue by danatcofo** [natemcmaster/DotNetCorePlugins#139]
Running a CORE 3.1 electron.net app and an internal class I'm storing in MemoryCache is throwing an InvalidCastException

```
System.InvalidCastException: [A]Prefix.Converters.SqlParser.SqlCacheItem cannot be cast to [B]Prefix.Converters.SqlParser.SqlCacheItem. Type A originates from 'Prefix.Converters.SqlRules, Version=0.0.0.0, Culture=neutral, PublicKeyToken=null' in the context 'Default' at location 'C:\repos\prefix.app\src\Prefix.App\obj\Host\bin\plugins\Prefix.Converters.SqlRules\Prefix.Converters.SqlRules.dll'. Type B originates from 'Prefix.Converters.SqlRules, Version=0.0.0.0, Culture=neutral, PublicKeyToken=null' in the context 'Default' at location 'C:\repos\prefix.app\src\Prefix.App\obj\Host\bin\plugins\Prefix.Converters.SqlRules\Prefix.Converters.SqlRules.dll'.
   at Microsoft.Extensions.Caching.Memory.CacheExtensions.GetOrCreate[TItem](IMemoryCache cache, Object key, Func`2 factory)
   at Prefix.Converters.SqlParser.GuduSqlParser.Parse(String sql, Boolean collectCleanSql, EDbVendor sqlVendor, Boolean skipCache, Dictionary`2 incomingParams) in C:\repos\prefix.app\src\plugins\Prefix.Converters.SqlRules\SqlParser\GuduSqlParser.cs:line 1009
```

Of note:  

* type a and type b above are identical according to the error
* Internal class within the plugin and not shared or used outside of the plugin.

**To Reproduce**

Haven't created a clean reproduction but...

* Core 3.1
* using latest stable memory cache and standard dependency injection
* using latest of this library

sample code in plugin that breaks

```
internal class SqlCacheItem
{
	public string StrippedSql { get; set; }
	public string Display { get; set; }
	public bool IsMsSqlSproc { get; set; } = false;
	public short ParsedOutParamsCount { get; set; } = 0;
}
// _sqlCache is IMemoryCache
_sqlCache.GetOrCreate(workItem.Statement.hash, entry =>
{
	entry.SlidingExpiration = TimeSpan.FromHours(1);
	return new SqlCacheItem
		{
			StrippedSql = "lorem ipsum",
			IsMsSqlSproc = true,
			ParsedOutParamsCount = 0,
			Display = "lorem ipsum",
		};
});

```

**Expected behavior**
I would expect that IMemoryCache would return the same instance back, but it casts back to some seemingly unknown/different class

I think I'm missing something in setup or something but... if I am then I'm blind I think.  Since this isn't an issue with shared types on its face, is there an issue with lacking shared types under the covers even though this is an internal class only?

**Comment by danatcofo** [comment]
NOTE: I'm getting around this currently by serializing the object as a string for caching purposes.
