### ISSUE TITLE
ReflectionTypeLoadException saying a method is not implemented when it is

### ISSUE THREAD

**Issue by DanaEpp** [natemcmaster/DotNetCorePlugins#17]
I don't believe this is a bug in DotNetCorePlugins, but I could really use some help understanding why I can't get it working. 

First the exception I am seeing:

```
{System.Reflection.ReflectionTypeLoadException: Unable to load one or more of the requested types.
Method 'ListAsync' in type 'TestPlugin' from assembly 'TestPlugin, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null' does not have an implementation.
   at System.Reflection.RuntimeModule.GetTypes(RuntimeModule module)
   at System.Reflection.RuntimeModule.GetTypes()
   at System.Reflection.Assembly.GetTypes()
   at PluginManager.LoadPlugins(String pluginsDir) in C:\Users\me\source\repos\TestSol\TestFramework\PluginManager.cs:line 29
   at TestConsole.Program.TestDataCollection() in C:\Users\me\source\repos\TestSol\TestConsole\Program.cs:line 33
   at TestConsole.Program.<>c.<<Main>b__0_0>d.MoveNext() in C:\Users\me\source\repos\TestSol\TestConsole\Program.cs:line 19
System.TypeLoadException: Method 'ListAsync' in type 'TestPlugin' from assembly 'TestPlugin, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null' does not have an implementation.}	System.Exception {System.Reflection.ReflectionTypeLoadException}
```

I have three projects (all netcoreapp2.1) in my solution (TestSol):

1. A base framework for the plugin called `TestFramework` that exposes an interface called `IDataCollectorPlugin`. It also has the class to load the plugins called `PluginManager`.
2. A sample plugin implementing this interface called `TestPlugin`
3. A console app called `TestConsole` that is used to load everything up.

So here is the code for TestPlugin:

```
   public class TestPlugin : IDataCollectorPlugin
    {
        public string PluginName
        {
            get => "Test";
        }

        public async Task<List<ResourceItemSummary>> ListAsync(ServiceClientCredentials creds, string subscriptionId)
        {
            // ACTUAL WORK HERE
        }
    }
```

Here is the interface:

```
public interface IDataCollectorPlugin
    {
        string PluginName { get; }

        Task<List<ResourceItemSummary>> ListAsync(ServiceClientCredentials creds, string subscriptionId);
    }
```

I can't understand why it says `ListAsync()` has not been implemented when it clearly has. This exception is thrown when I call .GetTypes() from your sample in the foreach loop:

```
foreach (var pluginType in loader
                     .LoadDefaultAssembly()
                     .GetTypes()
                     .Where(t => typeof(IDataCollectorPlugin).IsAssignableFrom(t) && !t.IsAbstract))
                {
                    IDataCollectorPlugin plugin = (IDataCollectorPlugin)Activator.CreateInstance(pluginType);
                    Console.WriteLine($"Created plugin instance '{plugin.PluginName}'.");
                }
```

Any ideas what I am doing wrong in trying to scaffold this plugin?

**Comment by onovotny** [comment]
Do you have a simple repro solution that demonstrates this specific exception? It would be a helpful starting point.

**Comment by darren4ten** [comment]
I have same issue since I downgrade the .net core from 2.2 to 2.1, no any issue for 2.2 but 2.1, and I tried  add the type of the method but with no luck, could anyone give a hand?
![image](https://user-images.githubusercontent.com/18156998/71396407-edfb5000-2654-11ea-9b6d-b507d265ed20.png)
![image](https://user-images.githubusercontent.com/18156998/71396421-fbb0d580-2654-11ea-8f3a-31b735695be4.png)
