### ISSUE TITLE
Duplicated key when loading assembly.

### ISSUE THREAD

**Issue by tuanhd9173** [natemcmaster/DotNetCorePlugins#92]
Dear,

I have created a small example with 2 plugins. But it cause duplicated key exception when loading first plugin dll with PluginLoader.CreateFromAssemblyFile().

Could you please check the sample and point out some things wrong?
Please refer attached file for the solution.

Thank so much.
Tuan Ha
[PlugEx.zip](https://github.com/natemcmaster/DotNetCorePlugins/files/3904730/PlugEx.zip)

**Comment by natemcmaster** [comment]
I tried running your sample bug didn't get any errors. Can you provide more details?

**Comment by natemcmaster** [comment]
Correction: I tried running your sample but\*\* didn't get any errors. Can you provide more details?

**Comment by tuanhd9173** [comment]
Dear Nate,

On my PC, it throw exception at the first loading as below image.

![image](https://user-images.githubusercontent.com/37283535/70315190-a2bb0200-184b-11ea-9051-e2ae1dff9d19.png)

**Comment by natemcmaster** [comment]
Can you share a stack trace and a process dump?

**Comment by tuanhd9173** [comment]
Dear Nate,

Please find the dump file as below link:
https://drive.google.com/open?id=1qgpjm7xRqeF9h65s3PQ241WZp6sCQsIo

And stack trace:

at System.ThrowHelper.ThrowAddingDuplicateWithKeyArgumentException[T](T key)
   at System.Collections.Generic.Dictionary`2.TryInsert(TKey key, TValue value, InsertionBehavior behavior)
   at System.Runtime.Loader.AssemblyDependencyResolver..ctor(String componentAssemblyPath)
   at McMaster.NETCore.Plugins.Loader.ManagedLoadContext..ctor(String mainAssemblyPath, IReadOnlyDictionary`2 managedAssemblies, IReadOnlyDictionary`2 nativeLibraries, IReadOnlyCollection`1 privateAssemblies, IReadOnlyCollection`1 defaultAssemblies, IReadOnlyCollection`1 additionalProbingPaths, IReadOnlyCollection`1 resourceProbingPaths, Boolean preferDefaultLoadContext, Boolean isCollectible, Boolean loadInMemory)
   at McMaster.NETCore.Plugins.Loader.AssemblyLoadContextBuilder.Build()
   at McMaster.NETCore.Plugins.PluginLoader..ctor(PluginConfig config)
   at McMaster.NETCore.Plugins.PluginLoader.CreateFromAssemblyFile(String assemblyFile, Action`1 configure)
   at McMaster.NETCore.Plugins.PluginLoader.CreateFromAssemblyFile(String assemblyFile, Type[] sharedTypes, Action`1 configure)
   at McMaster.NETCore.Plugins.PluginLoader.CreateFromAssemblyFile(String assemblyFile, Type[] sharedTypes)
   at PlugEx.Startup.LoadLibrary(String pluginFile) in D:\Working\PlugEx\PlugEx\Startup.cs:line 32
   at PlugEx.Startup..ctor(IConfiguration configuration) in D:\Working\PlugEx\PlugEx\Startup.cs:line 26
--------------------

**Comment by natemcmaster** [comment]
So, the bug is being thrown from a .NET Core API itself, so this is beyond my control to help you with. I would recommend opening this issue at https://github.com/dotnet/runtime. Make sure to include the .deps.json file that should be at "D:\Working\PlugEx\Plug1\\bin\\Debug\\netstandard2.0\\plug1.deps.json"

```
System.Runtime.Loader.AssemblyDependencyResolver..ctor(String componentAssemblyPath)
```

**Comment by natemcmaster** [comment]
Oh, and by the way, you should be able to reproduce this independently of my library with this code.

```c#
var resolver = new System.Runtime.Loader.AssemblyDependencyResolver(@"D:\Working\PlugEx\Plug1\bin\Debug\netstandard2.0\plug1.dll");
```

**Comment by tuanhd9173** [comment]
Thank you, Nake.

**Comment by natemcmaster** [comment]
Closing as this issue is external to this project, so there isn't an action I can take on this.
